- name: Add Ubuntu apt signing key
  apt_key:
    url: "{{ ubuntu_apt.key_url }}"
    state: present
  when: ubuntu_apt.key_url | default(false)

- name: Remove old sources.list.d files
  file:
    path: "/etc/apt/sources.list.d/{{ item }}"
    state: absent
  with_items:
    - security-ubuntu-archive.list
    - ubuntu-archive.list
    - ubuntu-archive-backports.list
    - ubuntu-archive-updates.list

- name: Check for i386 architecture support
  shell: dpkg --print-foreign-architectures | grep i386
  register: check_for_i386_apt_support
  failed_when: check_for_i386_apt_support.rc == 0
  ignore_errors: true
  changed_when: false

- name: Remove i386 architecture from apt
  command: dpkg --remove-architecture i386
  when: check_for_i386_apt_support is failed
  changed_when: true

- name: Generate apt sources.list
  template:
    src: apt/sources.list.j2
    dest: /etc/apt/sources.list
    mode: '0644'
  register: sources_list

- name: Update apt indices
  apt:
    update_cache: true
  when: sources_list.changed # noqa: no-handler

# Prevent upgrades to Cinc or Chef >= 15
- name: Install apt preferences file to pin Chef
  copy:
    src: apt/99chef
    dest: /etc/apt/preferences.d/99chef
    mode: '0644'
