- name: Install chrony
  apt:
    name: chrony

- name: Configure chrony
  template:
    src: chrony/chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    mode: '0644'
  register: chrony

- name: Configure chrony defaults
  template:
    src: chrony/default.j2
    dest: /etc/default/chrony
    mode: '0644'
  register: chrony_defaults

- name: Install service to monitor sources after getting a default route
  block:
    - name: Install the systemd unit
      copy:
        content: |
          [Unit]
          Description=Wait for default route and bring chrony sources online
          After=bird.service chrony.service
          Requires=chrony.service

          [Service]
          Type=oneshot
          ExecStart=/bin/sh -c 'while [ -z "$(/sbin/ip route list default)" ]; do sleep 1; done'
          ExecStartPost=/usr/bin/chronyc online
          TimeoutStopSec=1

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/wait-for-default-route.service
        mode: '0644'
      register: chrony_custom

    - name: Enable the service at reboot
      service:
        name: wait-for-default-route
        daemon_reload: true
        enabled: true
      when: chrony_custom.changed # noqa: no-handler

- name: Restart chrony
  systemd:
    name: chrony
    state: restarted
  when: chrony.changed or chrony_defaults.changed
